### ISSUE TITLE
Wiredep won't include color-js dependency into index.html because malformed .bower.json

### ISSUE THREAD

**Issue by stimg** [brehaut/color-js#20]
Please add 
`"main": "color.js"`
line into `.bower.json` file in order `wiredep` can recognize this dependency and inject it into index.html.

Thanks!

**Comment by brehaut** [comment]
Thanks for reporting the issue. If you could please make a pull request for this fix that would be great. I don't use bower myself so have no way to test it.

**Comment by stimg** [comment]
The `bower.json` file in the current version (1.0.2) here is correct. The version **1.0.1**, which I get after `bower install color-js`, contains no `bower.json` file but `.bower.json` only:
```
{
  "name": "color-js",
  "homepage": "https://github.com/brehaut/color-js",
  "version": "1.0.1",
  "_release": "1.0.1",
  "_resolution": {
    "type": "version",
    "tag": "v1.0.1",
    "commit": "48bf44960325075e5e8547f985b06dd73d027450"
  },
  "_source": "https://github.com/brehaut/color-js.git",
  "_target": "^1.0.1",
  "_originalSource": "color-js",
  "_direct": true
}
```
Please update you bower module to current version.

Great job!
Thank you!

**Comment by brehaut** [comment]
Sorry about the late reply. 

I down own the bower module. Someone else published it there without contacting me, so I can't perform an update there sorry.
