### ISSUE TITLE
Explain Ratio vs Value

### ISSUE THREAD

**Issue by natew** [brehaut/color-js#24]
Reading over readme this isn't very clear to me. Ratio is basically 0-1 of 100%, where amount is a percent?

**Comment by brehaut** [comment]
* A ratio multiplies the existing property by the ratio. 
* An amount is just added directly to the existing value. 

So if you have a red value of 150 and you apply a ratio of 0.5 the new color has a red value of 75. If you then add an amount of 25 to that color the final color will have a red value of 100.
