### ISSUE TITLE
Cannot import in Angular2 with typescript 2.1

### ISSUE THREAD

**Issue by GianlucaMaggio** [brehaut/color-js#30]
I cannot import the library using Angular 2 with Typescript 2.1.

In every mode I try to import the module the system tell me:

> File ... node_modules/color-js/color.d.ts is not a module

I found a solution, but changing the colors.d.ts adding at last line:

`
export = net.brehaut.Color;
`

In this way I can import with:

`import Color from "color-js/color";`

![image](https://cloud.githubusercontent.com/assets/1485446/22158858/a0043476-df3e-11e6-8d72-aaf830b9f7b3.png)

**Comment by brehaut** [comment]
Pull requests welcome

**Comment by GianlucaMaggio** [comment]
I'll pull a request with this change but I'm not able to make it working on every module loader. This works with systemjs but not with commonjs. I'm a bit confused on how is the right way of exporting for all module loaders.
